# Generated by Django 5.0.1 on 2024-03-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iptmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='iptmentors',
            options={},
        ),
        migrations.AlterModelOptions(
            name='iptstudent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='updatestudent',
            options={},
        ),
    ]
