# Generated by Django 5.0.1 on 2024-03-14 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_iptmaster_options_alter_iptmentors_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptstudent',
            name='iptcid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.iptmaster'),
            preserve_default=False,
        ),
    ]
