# Generated by Django 5.0.1 on 2024-03-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_iptstudent_iptcid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatestudent',
            options={'managed': False},
        ),
    ]
