# Generated by Django 5.0.1 on 2024-03-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_updatestudent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admincourse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hrmadpositionheld',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hrmpersonnelinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sisstudentinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='updatestudent',
            options={},
        ),
    ]
